import os
import streamlit as st 
import pandas as pd
import streamlit.components.v1 as components
from src.ingestor import fetch_live_market_data
from src.agent import run_agent_analysis

st.set_page_config(page_title="Sentinel Fraud 2026", layout="wide")

# 1. Page Configuration
st.set_page_config(
    page_title="Sentinel Fraud AI 2026",
    layout="wide",
    page_icon="🛡️"
)

st.markdown("""
    <style>
    .main { background-color: #0e1117; }
    .stMetric { background-color: #1f2937; padding: 15px; border-radius: 10px; }
    </style>
    """, unsafe_allow_exists=True)

st.title("🛡️ Sentinel-Graph AI")
st.markdown("### Graph-Based Fraud Detection & Forensic Analysis")
st.write("---")

# 2. Sidebar Control - The Ingestion Logic
st.sidebar.header("Data Control Center")
if st.sidebar.button('🚀 Run Live Market Scan'):
    with st.spinner('Ingesting & Analyzing...'):
        # This calls your ingestor script
        df_new = fetch_live_market_data()
        if df_new is not None:
            st.sidebar.success(f"Successfully fetched {len(df_new)} tokens.")
            st.sidebar.info("Note: Run 'python main.py' to update GNN weights.")
        else:
            st.sidebar.error("API Connection Failed.")

# 3. MAIN DASHBOARD LOGIC
processed_path = 'data/processed/cleaned_market_data.csv'

if os.path.exists(processed_path):
    # Load the results generated by main.py
    df = pd.read_csv(processed_path)

    # Metrics Row
    c1, c2, c3 = st.columns(3)
    total_suspicious = int(df['ai_prediction'].sum())
    c1.metric("Live Market Scan", f"{len(df)} Tokens")
    c2.metric("GNN Fraud Alerts", total_suspicious, delta=total_suspicious, delta_color="inverse")
    c3.metric("System Security", "Protected", delta="Active")

    st.write("---")

    # Visualization Row
    col1, col2 = st.columns([2,1])
    
    with col1:
        st.subheader("🌐 Fraud Network Visualization")
        # Load the HTML file from your notebooks folder
        html_path = "notebooks/final_eda_network.html"
        if os.path.exists(html_path):
            with open(html_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            components.html(html_content, height=600, scrolling=True)
        else:
            st.warning("⚠️ Network graph file not found. Please run 'main.py' first.")
        
    with col2:
        st.subheader("🤖 LangGraph Analyst Reports")
        # Get the tokens flagged by the AI
        suspicious_tokens = df[df['ai_prediction'] == 1].head(5)

        if not suspicious_tokens.empty:
            for _, row in suspicious_tokens.iterrows():
                # Trigger the LangGraph State Machine (Investigator -> Reporter)
                with st.spinner(f"Agent investigating {row['symbol']}..."):
                    report = run_agent_analysis(row['symbol'], row['volume_mcap_ratio'])
                
                with st.expander(f"🚩 Analysis: {row['symbol']}", expanded=True):
                    st.markdown(f"**Risk Score:** High")
                    st.write(report)
        
        else:
            st.success("✅ No critical threats identified by GNN.")
    
    # 4. Data Deep-Dive Table
    st.write("---")
    st.subheader("📊 Intelligence Data Deep-Dive")
    # Highlight suspicious rows in the table
    def highlight_fraud(s):
        return ['background-color: #721c24' if s.ai_prediction == 1 else '' for _ in s]
    
    st.dataframe(
        df[['symbol', 'name', 'current_price', 'volume_mcap_ratio', 'ai_prediction']],
        use_container_width=True
    )

else:
    st.info("👋 Welcome! To start, please run **'python main.py'** in your terminal to process data and train the AI.")