import sys
import os
import time
import streamlit as st
import pandas as pd
import streamlit.components.v1 as components
import warnings

st.sidebar.title("🔑 System Configuration")

# Upload .env if keys are expired
uploaded_env = st.sidebar.file_uploader("Upload .env if keys expire", type=["env", "txt"])

if uploaded_env:
    # Read the file and inject keys into os.environ
    for line in uploaded_env.read().decode("utf-8").splitlines():
        if "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            os.environ[key.strip()] = value.strip()
    st.sidebar.success("✅ Forensic Keys Updated!")

# Centralized Key Loader Function
def get_key(name):
    # Order of Priority: Manual Upload/Env Variable -> Streamlit Cloud Secrets
    return os.getenv(name) or st.secrets.get(name)

# Inject keys into the environment so src/agent.py can find them automatically
os.environ["GOOGLE_API_KEY"] = get_key("GOOGLE_API_KEY") or ""
os.environ["COINGECKO_API_KEY"] = get_key("COINGECKO_API_KEY") or ""
os.environ["IPQS_API_KEY"] = get_key("IPQS_API_KEY") or ""

# 4. Global Offline Check
if not os.environ.get("GOOGLE_API_KEY"):
    st.sidebar.error("🛡️ Sentinel Analyst Offline. Please provide an API key.")

# Path setup 
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(BASE_DIR)


from src.ingestor import fetch_live_market_data
from src.agent import run_agent_analysis

# 1. Page Configuration
st.set_page_config(
    page_title="Sentinel-Graph AI",
    page_icon="🛡️",
    layout="wide"  
)

# 2. Enhanced Forensic CSS
st.markdown("""
    <style>
    /* 1. Global Font Size reduction */
    html, body, [class*="css"], .stMarkdown, p, span {
        font-size: 0.95rem !important;
    }

    .main {
        background-color: #ffffff !important;
    }

    /* Force Metric Box to be Black */
    [data-testid="stMetric"] {
        background-color: #000000 !important;
        border: 1px solid #333333 !important;
        padding: 10px !important; /* Slightly smaller padding */
        border-radius: 10px !important;
        box-shadow: 0 4px 10px rgba(0,0,0,0.3) !important;
    }

    /* Force Titles to be Pure White & Slightly Smaller */
    [data-testid="stMetricLabel"] p {
        color: #ffffff !important;
        opacity: 1 !important;
        font-weight: 700 !important;
        font-size: 0.85rem !important;
    }

    /* THE FIX: Targeting text and Delta (the colored arrow/value) */
    [data-testid="stMetricValue"], [data-testid="stMetricDelta"] > div {
        opacity: 1 !important;
    }

    /* NEON GREEN GLOW: Market Sample (1), Avg Risk (3), System Engine (4) */
    /* Target children to include the Delta arrows and values */
    [data-testid="column"]:nth-child(1) [data-testid="stMetricValue"] *,
    [data-testid="column"]:nth-child(1) [data-testid="stMetricDelta"] *,
    [data-testid="column"]:nth-child(3) [data-testid="stMetricValue"] *,
    [data-testid="column"]:nth-child(3) [data-testid="stMetricDelta"] *,
    [data-testid="column"]:nth-child(4) [data-testid="stMetricValue"] *,
    [data-testid="column"]:nth-child(4) [data-testid="stMetricDelta"] * {
        color: #00ff00 !important;
        text-shadow: 0 0 8px #00ff00, 0 0 15px #00ff00 !important;
        font-weight: 900 !important;
        -webkit-text-fill-color: #00ff00 !important;
    }

    /* NEON RED GLOW: GNN Alerts (2) */
    [data-testid="column"]:nth-child(2) [data-testid="stMetricValue"] *,
    [data-testid="column"]:nth-child(2) [data-testid="stMetricDelta"] * {
        color: #ff0000 !important;
        text-shadow: 0 0 8px #ff0000, 0 0 15px #ff0000 !important;
        font-weight: 900 !important;
        -webkit-text-fill-color: #ff0000 !important;
    }

    /* Table visibility fix */
    [data-testid="stDataFrame"] {
        border: 1px solid #e6e9ef;
        border-radius: 5px;
    }
    </style>
    """, unsafe_allow_html=True)

st.title("🛡️ Sentinel-Graph AI")
st.markdown("### Graph-Based Fraud Detection & Forensic Analysis")

# 2. Sidebar Control - The Ingestion Logic
st.sidebar.header("Data Control Center")
if st.sidebar.button('🚀 Run Live Market Scan'):
    with st.spinner('Ingesting & Analyzing...'):
        # This calls your ingestor script
        df_new = fetch_live_market_data()
        if df_new is not None:
            st.sidebar.success(f"Successfully fetched {len(df_new)} tokens.")
            st.sidebar.info("Note: Run 'python -m main' to refresh GNN results.")

if st.sidebar.button('🧹 Reset AI Analysis'):
    st.cache_data.clear()
    st.sidebar.success("Cache Cleared! Fresh reports will be generated.")
    
# 3. Load Processed Data (The results from main.py)
processed_path = os.path.join(BASE_DIR, 'data', 'processed', 'sentinel_forensic_results.csv')

if os.path.exists(processed_path):
    # Load the results generated by main.py
    df = pd.read_csv(processed_path)

    # --- TOP ROW: KPI METRICS ---
    c1, c2, c3, c4 = st.columns(4)
    total_suspicious = int(df['ai_prediction'].sum())
    avg_risk = df['risk_score'].mean() * 100
    
    c1.metric("Market Sample", f"{len(df)} Tokens", delta="LIVE")
    c2.metric("GNN Alerts", f"{total_suspicious}",delta="CRITICAL", delta_color="inverse")
    c3.metric("Avg Market Risk", f"{avg_risk:.1f}%")
    c4.metric("System Engine", "gemini")

    st.divider()

    # --- MIDDLE ROW: GRAPH & AGENT ---
    col1, col2 = st.columns([3, 1])
    
    with col1:
        st.subheader("🌐 Network Contagion Map")
        # Load the HTML file from your notebooks folder
        html_path = os.path.join(BASE_DIR, "notebooks", "final_eda_network.html")
        if os.path.exists(html_path):
            with open(html_path, 'r', encoding='utf-8') as f:

                components.html(f.read(), height=700, scrolling=True)
        else:
            st.warning("⚠️ Adjacency Map not found. Run main.py first.")
        
    with col2:
        st.subheader("🤖 Forensic Agent Reports")
        
        # Sort by highest risk score from GNN
        top_risk = df.nlargest(5, 'risk_score')

        if not top_risk.empty:
            for _, row in top_risk.iterrows():
                # Display Risk Progress Bar
                risk_pct = float(row['risk_score'])
                st.write(f"**{row['symbol'].upper()}**")
                st.progress(risk_pct)
                
                with st.expander(f"View Report (Risk: {risk_pct*100:.1f}%)"):
                    with st.spinner("Generating Agentic Narrative..."):
                        # Updated to pass the full state dictionary to the new Agent
                        try:

                            agent_input = {
                                "symbol": row['symbol'],
                                "ratio": row['volume_mcap_ratio'],
                                "price_volatility": row.get('price_spread_percentage', 0),
                                "roi_missing": bool(row.get('is_roi_missing', False)),
                                "is_gnn_flagged": bool(row['ai_prediction']),
                                "risk_score": float(row['risk_score'])
                            }
                            report = run_agent_analysis(agent_input)

                            if report:
                                st.markdown(report)
                            else:
                                st.error("🕵️ Agent is busy. Please wait 30s and refresh.")
                        
                        except Exception as e:
                            # If the AI fails, show a manual forensic summary instead of a crash
                            st.warning("⚠️ AI Quota reached.")
                                                  
                
        else:
            st.success("✅ No critical threats identified.")
    
    # --- BOTTOM ROW: DATA GRID ---
    st.divider()
    st.subheader("📊 Intelligence Data Deep-Dive")

    # Highlight suspicious rows in the table
    df_sorted = df.sort_values(by=['ai_prediction', 'risk_score'], ascending=[False, False])

    
    def highlight_fraud(row):
        if row.ai_prediction == 1:
            return ['background-color: #7f1d1d; color: white; font-weight: bold;'] * len(row)
        return [''] * len(row)

    display_cols = ['symbol', 'current_price', 'volume_mcap_ratio', 'risk_score', 'ai_prediction']
    
    
    st.dataframe(
        df_sorted[display_cols].style.apply(highlight_fraud, axis=1).format({
            'risk_score': '{:.2%}',
            'current_price': '${:.4f}',
            'volume_mcap_ratio': '{:.2f}'
        }),
        width='stretch',
        hide_index=True
    )

else:
    st.warning("👋 No processed data found. Please run **'python -m main'** to generate forensic results.")